jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      $HOME/.cargo/bin/rustc -vV
      $HOME/.cargo/bin/cargo -vV
    displayName: Install Rust
  - script: $HOME/.cargo/bin/cargo check --verbose --all-features
    displayName: Cargo check all features
  - script: $HOME/.cargo/bin/cargo test --verbose --no-fail-fast -- --nocapture
    displayName: Cargo test
