jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      stable-x64:
        channel: stable
        target: x86_64-pc-windows-msvc
      stable-x86:
        channel: stable
        target: i686-pc-windows-msvc
      beta-x64:
        channel: beta
        target: x86_64-pc-windows-gnu
      beta-x86:
        channel: beta
        target: i686-pc-windows-gnu
      nightly-x64:
        channel: nightly
        target: x86_64-pc-windows-msvc
  steps:
  - script: |
        curl -sSf -o rustup-init.exe https://win.rustup.rs
        rustup-init -yv --default-toolchain $(channel) --default-host $(target)
        set PATH=%PATH%;%USERPROFILE%\.cargo\bin
        echo "##vso[task.setvariable variable=PATH]%PATH%;%USERPROFILE%\.cargo\bin"
        rustc -vV
        cargo -vV
    displayName: Install Rust
  - script: cargo check --verbose --all-features
    displayName: Cargo check all features
  - script: cargo test --verbose --no-fail-fast -- --nocapture
    displayName: Cargo test
